# install redis and vector
sudo apt install redis
curl --proto '=https' --tlsv1.2 -sSfL https://sh.vector.dev | sudo bash

# edit vector config
ubuntu@ubuntu22:/etc/vector$ cat vector.yaml
sources:
  nginx_logs:
    type: file
    include: ["/var/log/nginx/access.log"]
    read_from: "beginning"

  falco_logs:
    type: file
    include: ["/var/log/falco.json"]
    read_from: "beginning"

transforms:
  add_nginx_sensor:
    type: remap
    inputs: ["nginx_logs"]
    source: |
      .sensor = "nginx"

  add_falco_sensor:
    type: remap
    inputs: ["falco_logs"]
    source: |
      .sensor = "falco"

sinks:
  nginx_redis_sink:
    type: redis
    inputs: ["add_nginx_sensor"]
    url: "redis://127.0.0.1:6379"
    key: "log_nginx"
    data_type: "list"
    encoding:
      codec: "json"

  falco_redis_sink:
    type: redis
    inputs: ["add_falco_sensor"]
    url: "redis://127.0.0.1:6379"
    key: "log_falco"
    data_type: "list"
    encoding:
      codec: "json"

# validate configs
vector validate /etc/vector/vector.yaml

# test sending logs
redis-cli -h 127.0.0.1 -p 6379
# get log from beging of list
LPOP log_envoy
# get log from end of list
RPOP log_envoy