version: "3.8"

services:

  etcd:
    image: bitnamilegacy/etcd:3.5.11
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379"

  apisix:
    build: .
    container_name: apisix
    depends_on:
      - etcd
    ports:
      - "9080:9080"
      - "9180:9180"

  apisix-dashboard:
    image: apache/apisix-dashboard:3.0.1-alpine
    container_name: apisix-dashboard
    depends_on:
      - etcd
    ports:
      - "9000:9000"
    volumes:
      - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
